# -*- conf -*-
title=Terminal
locked-title=no
font=mono:size=12, Noto Color Emoji:size=11
bold-text-in-bright=yes

[bell]
notify=yes
command-focused=yes

[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste

[colors]
alpha=0.80
foreground=c8c6d7        # txF
background=1b0329        # Fondo oscuro personalizado, estilo bg profundo

# Normal colors
regular1=9d4edd # Red
regular2=00ff00 # Green
regular7=bfacc8 # White

# Bright colors
bright1=620f92
bright2=137900
bright7=f5dfff

[scrollback]
lines=100000
# multiplier=3.0
# indicator-position=relative
# indicator-format=

[cursor]
style=underline
color=FF0000 39ff14
blink=yes

[mouse]
hide-when-typing=yes
